[[redirects]]
  from = "/api/*"
  # Paste your unique webhook.site URL here
  to = "https://webhook.site/https://webhook.site/3df8c09e-cc97-41c5-88b3-5d3417311fcb/:splat"
  status = 200
  force = true

  [redirects.headers]
    User-Agent = "A Web Reddit Client by Miles"


  